strategy:
  matrix:
    windows:
      imageName: windows-2019
      pythonVersion: 3.7
    linux:
      imageName: ubuntu-16.04
      pythonVersion: 3.7
    umac:
      imageName: macos-10.13
      pythonVersion: 3.7

pool:
  vmImage: $(imageName)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pythonVersion)
      architecture: "x64"

  - script: |
      sudo apt update
      sudo apt install python3-tk xvfb
    displayName: "Install system dependencies in Linux"
    condition: eq(variables['Agent.OS'], 'Linux')

  - script: |
      pip install -e .
    displayName: "Install prerequisites"

  - script: |
      xvfb-run -a python setup.py -q test
    condition: and(succeededOrFailed(), eq(variables['Agent.OS'], 'Linux'))
    displayName: "Run tests in Linux"

  - script: |
      python setup.py -q test
    condition: and(succeededOrFailed(), ne(variables['Agent.OS'], 'Linux'))
    displayName: "Run tests in Windows or MacOS"

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/test-*.xml"
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "**/coverage.xml"
      reportDirectory: "**/htmlcov"
    condition: succeededOrFailed()
