pool:
  vmImage: "ubuntu-16.04"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.7
      architecture: "x64"

  - script: |
      sudo apt update
      sudo apt install python3-tk xvfb
    displayName: "Install system dependencies"

  - script: |
      pip install -e .
    displayName: "Install prerequisites"

  - script: |
      xvfb-run -a python setup.py -q test
    condition: succeededOrFailed()
    displayName: "Run tests"

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/test-*.xml"
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "**/coverage.xml"
      reportDirectory: "**/htmlcov"
    condition: succeededOrFailed()
