strategy:
  matrix:
    linux:
      imageName: ubuntu-16.04
    windows:
      imageName: windows-2019
      pythonVersion: 3.7
    umac:
      imageName: macos-10.13
      pythonVersion: 3.7

pool:
  vmImage: $(imageName)

steps:
  - script: |
      docker build -t strainmap-test .
      docker run --rm -v $(pwd)/reports:/usr/src/app/reports strainmap-test
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: "Run tests in Linux"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(pythonVersion)
    condition: ne(variables['Agent.OS'], 'Linux')

  - script: |
      pip install -e .
      python setup.py -q test
    condition: ne(variables['Agent.OS'], 'Linux')
    displayName: "Run tests in Windows and macOS"

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/junit.xml"
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "**/coverage.xml"
      reportDirectory: "**/coverage"
    condition: succeededOrFailed()
