# General configuration for the net
[Net]
model_name = "UNet"
img_height = 512
img_width = 512
nclasses = 1
filters = 64
batch_size = 8
epochs = 5
verbose = 1
callbacks = "None"
validation_split = 0.05
shuffle = true
initial_epoch = 0
steps_per_epoch = "None"
imgchannel = 4
model_file = "None"

# Configuration for the augmentation process
[augmentation]
times = 4
axis = 0
include_original = false

[[augmentation.non_active]]
method = "vertical_flip"
is_random = true

[[augmentation.active]]
method = "horizontal_flip"
is_random = true

[[augmentation.active]]
method = "rotation"
is_random = true
degree = 90
fill_mode = "constant"

[[augmentation.non_active]]
method = "elastic"
is_random = true
alpha = 720
sigma = 24

[[augmentation.non_active]]
method = "shift"
is_random = true
wrg = 0.10
hrg = 0.1
fill_mode = "constant"

[[augmentation.non_active]]
method = "shear"
is_random = true
intensity = 0.05
fill_mode = "constant"

[[augmentation.non_active]]
method = "zoom"
zoom_range = [1.2, 1.2]
border_mode = "constant"
axis = [0, 1]
