name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.25

        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: docs/requirements_docs.txt